### ISSUE TITLE
conjure-up openstack presents no cloud choices to choose from??

### ISSUE THREAD

**Issue by bmullan** [ubuntu/conjure-up#127]
ubuntu 16.04 w/latest updates

latest lxd v2.0.2

installed conjure-up using:
http://conjure-up.io/

via the 2 cmds:
$ sudo apt install conjure-up
$ conjure-up openstack|

The Choose a Cloud screen presents NO choices to choose from...?

![conjure-up choose a cloud screenshot](https://cloud.githubusercontent.com/assets/1682855/15987196/63e3b5d4-2fee-11e6-9345-c725a3a7897b.png)

**Comment by battlemidget** [comment]
@bmullan should be fixed now, I'm going to talk to the charmstore guys on monday to see if anything changed as it looks like my bundle was just removed with no obvious reason as to why

**Comment by bmullan** [comment]
Thanks for the info Adam. ..   My systems have been down for over a week
while I converted them all to Ubuntu 16.04 root on ZFS using 2 mirrored
vdevs os 2 2TB drives each.

Most of my delay was figuring out how to work around a grub bug with zfs
that is not yet fixed/avail in 16.04.

But I had seen a guy post about the conjure-up openstack prob on /r/lxc
subreddit but hadn't been able to try it myself till today...

Brian

**Comment by battlemidget** [comment]
fixed in 2.0.0.2
